---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Create a Blue Deployment by reading the definition from a local file
      k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8/deployment-blue.yml
        namespace: default

    - name: Wait
      shell: sleep 30


    - name: Create a Service object by reading the definition from a file
      k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8/service-blue.yml
        namespace: default

    - name: Create a Green Deployment by reading the definition from a local file
      k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8/deployment-green.yml
        namespace: default