apiVersion: v1
kind: Service
metadata:
  name: chat-blue
  labels:
    app: chat-blue
spec:
  selector:
    app: chat-blue
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 5000
  type: LoadBalancer
