apiVersion: v1
kind: Service
metadata:
  name: chat-green
  labels:
    app: chat-green
spec:
  selector:
    app: chat-green
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
